-- phpMyAdmin SQL Dump
-- version 4.0.4
-- http://www.phpmyadmin.net
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 03-05-2019 a las 16:23:24
-- Versión del servidor: 5.5.32
-- Versión de PHP: 7.0.32

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de datos: `u951310947_sic`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `talleres`
--

CREATE TABLE IF NOT EXISTS `talleres` (
  `id_taller` int(5) NOT NULL AUTO_INCREMENT,
  `taller` varchar(500) COLLATE utf8_spanish_ci NOT NULL,
  `taller_ing` varchar(500) COLLATE utf8_spanish_ci NOT NULL,
  `descripcion` text COLLATE utf8_spanish_ci NOT NULL,
  `descripcion_ing` text COLLATE utf8_spanish_ci NOT NULL,
  `dia` varchar(2) COLLATE utf8_spanish_ci NOT NULL,
  `mes` varchar(200) COLLATE utf8_spanish_ci NOT NULL,
  `ano` year(4) NOT NULL,
  `inicio` time NOT NULL,
  `fin` time NOT NULL,
  `tallerista` varchar(500) COLLATE utf8_spanish_ci NOT NULL,
  `capacidad` int(2) NOT NULL,
  `tipo` varchar(100) COLLATE utf8_spanish_ci NOT NULL,
  `foto` varchar(500) COLLATE utf8_spanish_ci NOT NULL,
  PRIMARY KEY (`id_taller`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci AUTO_INCREMENT=19 ;

--
-- Volcado de datos para la tabla `talleres`
--

INSERT INTO `talleres` (`id_taller`, `taller`, `taller_ing`, `descripcion`, `descripcion_ing`, `dia`, `mes`, `ano`, `inicio`, `fin`, `tallerista`, `capacidad`, `tipo`, `foto`) VALUES
(1, 'Parque Rufino Tamayo', 'Rufino Tamayo Park', 'En el corazón de municipio de San Pedro Garza García, se encuentra el parque Rufino Tamayo; parque que ofrece un espacio digno, seguro e incluyente para el goce de todos, haciendo honor al gran artista mexicano Rufino Tamayo. Acompáñanos a conocer este parque, su modelo de operación, sus retos y éxitos al posicionarse como un espacio único para el disfrute de los sampetrinos, visitantes, y muchos perros. Esta visita será guiada por la directora del parque y sus colaboradores para luego terminar con un momento de networking con los asistentes en este maravilloso escenario.', 'In the heart of the municipality of San Pedro Garza García, you will find Rufino Tamayo Park; a place that offers a dignified, safe and inclusive space for the enjoyment of everyone, honoring the great Mexican artist Rufino Tamayo. Join us to know this park, its operating model, challenges and successes by positioning itself as a unique space for the enjoyment of the neighbors and visitors. ', '14', 'Mayo', 2019, '15:00:00', '19:00:00', '', 50, 'Vivencial', 'rufino_tamayo.png'),
(2, 'Distrito Tec', 'District Tec', 'El DistritoTec es un polígono de 452 hectáreas ubicado al sur de la ciudad de Monterrey conformado por 24 colonias, 8,826 viviendas y 16,995 habitantes. Desde el 2012 este distrito surge como una iniciativa de regeneración urbana impulsada por el Tecnológico de Monterrey, ciudadanos, organizaciones y autoridades con el interés de colaborar para el beneficio de su comunidad. A partir del 2016 se llevan a cabo proyectos derivados del plan maestro del campus y del programa parcial de desarrollo urbano. Acompaña al comité vecinal del DistritoTec a conocer este espacio, las actividades artísticas, educativas y económicas que se desarrollan en la zona, así como los espacios públicos icónicos que rodean esta importante universidad.', 'The Tec District is a 452-hectare polygon located south of the city of Monterrey consisting of 24 neighborhoods, 8,826 homes and 16,995 inhabitants. Since 2012, this district has emerged as an urban regeneration initiative promoted by the Tecnológico de Monterrey, citizens, organizations and authorities with the interest of collaborating for the benefit of their community. As of 2016, projects derived from the campus master plan and the partial urban development program are carried out. Accompany the neighborhood committee of the Tec District to learn about this space, the artistic, educational and economic activities that take place in the area, as well as the iconic public spaces that surround this important university.', '14', 'Mayo', 2019, '15:00:00', '07:00:00', '', 50, 'Vivencial', 'distrito_tec.png'),
(3, 'Parque Ecológico Chipinque', 'Chipinque Ecological Park', 'El Parque Ecológico Chipinque tiene como principal finalidad brindar a las familias y comunidad en general un lugar de recreación y sano esparcimiento despertando el interés turístico para los visitantes. Este parque es una gran reserva ecológica que se encuentra ubicada en la sierra madre oriental; ahí se promociona la educación ambiental además de impulsar el conocimiento científico para lograr el desarrollo sustentable. Conoce este maravilloso espacio y encuéntrate con la naturaleza, flora y fauna de la región.\r\n\r\n', 'The main purpose of the Chipinque Ecological Park is to provide families and the community in general with a place of recreation and healthy living, awakening tourist interest for visitors. This park is a large ecological reserve that is located in the Eastern Sierra Madre; there environmental education is promoted in addition to promoting scientific knowledge to achieve sustainable development. Meet this wonderful space and meet with the nature, flora and fauna of the region.', '14', 'Mayo', 2019, '10:00:00', '14:00:00', '', 60, 'Vivencial', 'chipinque.png'),
(4, 'Barrio Antiguo de Monterrey', 'Old Neighborhood', 'Monterrey es una ciudad moderna e industrial que conserva sus raíces. Te invitamos a conocer el barrio antiguo, ahí se conserva el casco antiguo de la ciudad, el palacio del gobierno, palacio municipal, la catedral, el faro de comercio y otros edificios emblemáticos que conforman la Macro Plaza y que han formado parte de la historia de Monterrey. Sé testigo del paso del tiempo en el desarrollo económico y cultural de la ciudad conociendo uno de sus espacios icónicos. Visita el cerro del obispado en un tour turístico y complementa este taller con la participación de la Universidad Regiomontana con un recorrido al parque Purísima, parklet y pocketpark Calle Zarco, así con una actividad de diseño colaborativo en sitio.', 'Monterrey is a modern industrial city that maintains its roots. We invite you to visit the old neighborhood, where the the state and municipal government palace, the cathedral, the trade beacon and other emblematic buildings that make up the Macro Plaza and that have been part of the history are preserved. from Monterrey. Witness the passage of time in the economic and cultural development of the city knowing one of its iconic spaces.', '14', 'Mayo', 2019, '10:00:00', '14:00:00', '', 45, 'Vivencial', 'barrio_antiguo.png'),
(5, 'Centros Deportivos', 'Sport centers', 'El deporte es indispensable para el sano desarrollo del ser humano; los centros deportivos son espacios especializados para la realización de actividades recreativas y de alto rendimiento, ya que cuentan con los espacios adecuados, además de una gran oferta de clases y entrenamiento para todo aquel interesado en ser parte de ellas. Conoce la experiencia e infraestructura de Nuevo León administrando el Centro de Alto Rendimiento “Parque Niños Héroes” así como fomentando el deporte posicionándolo como uno de los estados que encabezan las listas de mayor actividad deportiva y mejores instalaciones en México.', 'Sport is essential for the healthy development of the human being; the sports centers are specialized spaces for the realization of recreational and high performance activities. Since they have the right spaces, in addition to a wide range of classes for anyone interested in being part of them. Learn about the experience and infrastructure of Nuevo León by administering these sites and promoting sports, positioning it as one of the states that lead the lists of the greatest sports activity and best facilities in Mexico.', '15', 'Mayo', 2019, '10:00:00', '14:00:00', '', 50, 'Vivencial', 'centro_deportivo.png'),
(6, 'La Experiencia Detrás de un Evento', 'The experience behind an event', 'Cada año Parque Fundidora es escenario de cientos de eventos, entre los que destacan eventos deportivos, de esparcimiento, culturales, sociales y de entretenimiento. En este taller descubriremos las implicaciones de cada tipo de evento, la logística para eventos simultáneos, la convivencia con el resto de los visitantes y la operación del parque. Incluye recorridos por las áreas más usadas para eventos y por el montaje de uno de los eventos más importantes de la temporada.', 'Each year Parque Fundidora is the scene of hundreds of sports, leisure, cultural, social and entertainment events. In this workshop we will discover the implications of each type of event, the logistics for simultaneous events, the coexistence with the rest of the visitors and the operation of the park. We will tours the areas most used for events and the assembly of one of the most important events of the season.', '14', 'Mayo', 2019, '15:00:00', '19:00:00', '', 60, 'Vivencial', 'detras_de_un_evento.png'),
(7, 'De Siderúrgica a Parque Urbano: La Transformación de Parque Fundidora', 'From steelmaker to urban park: the transformation of Parque Fundidora', 'La historia de Parque Fundidora se remonta a 1900 cuando la Compañía de Fierro y Acero de Monterrey, S.A. abrió sus puertas. Ahora, más de 100 años después, los vestigios de esta gran empresa acerera son escenario de un parque urbano de 144 hectáreas en el corazón de Monterrey. Desde el 2001 el Parque Fundidora ha sido declarado como Museo de Sitio de Arqueología Industrial, título otorgado por el Instituto Nacional de Antropología e Historia, siendo este el único en Latinoamérica.\r\n\r\nDurante el taller se hablará de la transformación que ha vivido el parque, de ser una compañía siderúrgica a convertirse en un parque urbano. Así como la selección de piezas museográficas y macro esculturas que conforman el parque actualmente.', 'The history of Parque Fundidora dates back to 1900 when the de Fierro y Acero de Monterrey, S.A. Company Opened its doors. Now, more than 100 years later, the vestiges of this great steel company are the scene of an urban park of 144 acres in the heart of Monterrey. Since 2001, the Parque Fundidora has been declared an Industrial Archeology Site Museum, a title granted by the National Institute of Anthropology and History, which is the only one in Latin America. During the workshop, we will talk about the transformation the park has undergone, from being a steel company to becoming an urban park. As well as the selection of museum pieces and macro sculptures that make up the park today.', '14', 'Mayo', 2019, '10:00:00', '14:00:00', '', 60, 'Vivencial', 'transformacion_parques_fundidora.png'),
(8, 'Navegando Paseo Santa Lucía', 'Navigating Paseo Santa Lucía', 'Paseo Santa Lucía tiene como principal atractivo su canal navegable, con un trayecto de 2.35km y una profundidad de 1,20mts, es considerado una de las 13 maravillas de México creadas por el hombre. A través de un recorrido en este emblemático atractivo turístico se podrá detallar su operación, mantenimiento y manejo de eventos especiales.', 'Paseo Santa Lucía has as its main attraction a canal, that runs over 2.35km and has a depth of 1.20mts. It is considered one of the 13 wonders of Mexico created by man. Through a tour of this emblematic tourist attraction you can learn about its operation, maintenance and handling of special events.', '15', 'Mayo', 2019, '15:00:00', '19:00:00', '', 60, 'Vivencial', 'paseo_santa_lucia.png'),
(9, 'Operando Parque Fundidora', 'Operating Parque Fundidora', 'Parque Fundidora tiene una extensión de 144 hectáreas, una pista de 3.4km, 23 fuentes, 2 lagos, 80 hectáreas de área verde y un canal artificial de 2.35km. Su mantenimiento es extenso y minucioso para dar una atención de calidad a los más de 8.5 millones de visitantes que se reciben al año. En este taller se compartirá la rutina operativa del parque, desde el riego y jardinería, mantenimiento de la infraestructura, diseño de nuevos proyectos, hasta la limpieza y seguridad.', 'Parque Fundidora has an area of ​​144 acres, a 3.4km track, 23 fountains, 2 lakes, 80 acres of green area and an artificial water canal of 2.35km. Its maintenance is extensive and meticulous to give an excellence service to the more than 8.5 million visitors per year. In this workshop the operational routine of the park will be shared; from irrigation and gardening, maintenance of the infrastructure, to new projects design, and cleaning and security.', '15', 'Mayo', 2019, '10:00:00', '14:00:00', '', 60, 'Vivencial', 'operando_parque_fundidora.png'),
(10, 'Cerro de la Campana, Mural Colosal y Participación Ciudadana', 'Cerro de la Campana, mural colosal and citizen participation.', 'En junio de 2018 concluyó una magna obra artística en la cual participan 54 artistas del todo el país perteneciente al "Colectivo Tomate", quienes pintaron 25,000 metros cuadrados de 290 casas. Colectivo Tomate es una organización civil con base en Puebla conformada por 20 artistas, abogados, arquitectos, diseñadores, nutriólogos y administradores que han intervenido alrededor de ocho ciudades en todo México para invitar a las personas a tomar acción en las calles para generar una transformación y demostrar el poder del ciudadano en las comunidades, así como fortalecer los lazos de las comunidades. ¡Conoce el mural colosal y aprende realizar intervenciones comunitarias!', 'In June 2018, a magnificent artistic work was concluded with the participation of 54 artists from all over the country belonging to the "Colectivo Tomate", who painted 25,000 square meters of 290 houses. Colectivo Tomate is a civil organization based in Puebla made up of 20 artists, lawyers, architects, designers, nutritionists and administrators who have intervened around eight cities throughout Mexico to invite people to take action in the streets to generate a transformation and demonstrate the power of the citizen in the communities, as well as strengthen the bonds of the communities. Get to know the mural colosal and learn to carry out community interventions!', '15', 'Mayo', 2019, '10:00:00', '14:00:00', '', 45, 'Vicencial', 'cultura_espacio_publico.png'),
(11, 'Vivero ORCOTEC, Muros y Techos Verdes', 'ORCOTEC nursery, walls and green roofs.', 'ORCOTEC es una constructora binacional, con más de 20 años de experiencia en diseñar, construir y mantener todo tipo de áreas verdes y jardines, cuyo centro de producción de árboles y plantas llamado “Vivero San Andrés” se encuentra en la ciudad de Monterrey; ahí, tienen una gran variedad de plantas y árboles de diferentes especies y dimensiones. A través del conocimiento de estos especialistas también podremos conocer los principios básicos y características generales de cuidado para la construcción y manteniendo de muros y techos verdes en nuestras ciudades o edificios ¡Sé parte de esta experiencia verde!', 'ORCOTEC is a binational construction company with more than 20 years of experience in designing, building and maintaining all types of green areas and gardens, whose center of production of trees and plants called "Vivero San Andrés" is located in the city of Monterrey; There, they have a great variety of plants and trees of different species and dimensions. Through the knowledge of these specialists we can also know the basic principles and general characteristics of care for the construction and maintaining of walls and green roofs in our cities or buildings. Be part of this green experience!', '15', 'Mayo', 2019, '10:00:00', '14:00:00', '', 60, 'Vivencial', 'techos_verdes.png'),
(12, 'Centros Culturales y el Espacio Público.', 'Cultural centers and public space.', 'La cultura y el espacio público tienen una relación estrecha e innegable, la cultura tiene la oportunidad de intervenir y expresarse en el espacio público el viceversa. En este taller el asistente tendrá la oportunidad de conocer proyectos comunitarios culturales en la ciudad de Monterrey al visitar dos esferas culturales, lugares de mediación cultural y artística comunitaria impulsada por el Consejo para la Cultura y las Artes de Nuevo León. Una ubicada en el municipio de el Carmen y otra en el municipio de García; ahí también conoceremos el parque lineal Valle de Lincoln.', 'Culture and public space have a close and undeniable relationship, culture has the opportunity to intervene and express itself in public space, vice versa. In this workshop the assistant will have the opportunity to meet cultural community projects in the city of Monterrey by visiting two cultural spheres, places of cultural mediation and community art promoted by the Council for Culture and the Arts of Nuevo León. One located in the municipality of El Carmen and another in the municipality of García; There we will also know the Lincoln Valley linear park.', '14', 'Mayo', 2019, '15:00:00', '19:00:00', '', 50, 'Vivencial', 'centros_culturales.png'),
(13, 'Vivero Municipal de San Pedro', 'Municipal nursery of San Pedro.', 'San Pedro es el único municipio de Nuevo León que tiene un vivero que da servicio a las necesidades del municipio, ahí se siembran y cuidan miles de arbustos, así como plantas decorativas que se utilizan en parques, camellones y otros espacios públicos. En este taller adquirirás conocimientos prácticos sobre como sembrar, trasplantar, y dar mantenimiento a plantas en un vivero municipal, las especies endémicas utilizadas además de cómo a través de la recoja de hojas diaria, se crea composta.', 'San Pedro is the only municipality in Nuevo Leon that has a nursery that serves the needs of the municipality, where thousands of bushes are sown and cared for, as well as decorative plants that are used in parks, ridges and other public spaces. In this workshop you will acquire practical knowledge on how to plant, transplant, and maintain plants in a municipal nursery, the endemic species used, as well as how, through daily leaf collecting, compost is created.', '14', 'Mayo', 2019, '10:00:00', '14:00:00', '', 45, 'Vivencial', 'vivero_municipal_san_pedro.png'),
(14, 'Conectando San Nicolás', 'Connecting San Nicolas.', 'En los últimos 3 años, San Nicolás de los Garza es un municipio que ha apostado por el espacio público, parques urbanos y espacios dignos de movilidad peatonal e imagen urbana. Por otro lado, la Universidad Autónoma de Nuevo León (UANL), ubicada en este municipio, ha creado dentro de su campus un sistema de movilidad eficiente para sus alumnos. En este taller aprenderás sobre conexiones y el reconocimiento del espacio público para cambiar realidades. Haremos una presentación contextual y visita a la UANL para conocer su proyecto CONECTA, para luego hacer un recorrido a pie de los nuevos andadores de la colonia Anáhuac, así como el parque Hundido, Gran Parque San Nicolás, Parques las Arboledas y haremos un recorrido de accesibilidad con silla de ruedas.', 'In the last 3 years, San Nicolas de los Garza is a municipality that has opted for public space, urban parks and spaces worthy of pedestrian mobility and urban image. On the other hand, the Autonomous University of Nuevo Leon (UANL), located in this municipality, has created within its campus an efficient mobility system for its students. In this workshop you will learn about connections and the recognition of public space to change realities. We will make a contextual presentation and visit the UANL to know your CONECTA project, then make a walking tour of the new walkers of the Anahuac colony, as well as the sunken park, San Nicolás Great Park, Las Arboledas Parks and we will make a tour of accessibility with wheelchair.', '15', 'Mayo', 2019, '15:00:00', '19:00:00', '', 45, 'Vivencial', 'conectando_san_nicolas.png'),
(15, 'Recaudación de Fondos', 'Fundraising', 'La sostenibilidad financiera de proyectos de espacio público es un reto al que múltiples asociaciones civiles, grupos vecinales, patronatos y fideicomisos se enfrentan. Los donativos particulares o corporativos, así como patrocinios y la organización de eventos benéficos son opciones para recaudar fondos exitosamente si son planeados estratégicamente. Aprende a desarrollar campañas financieras y asegura el sostenimiento económico de tu parque a largo plazo en este taller curricular.', 'The financial sustainability of public space projects is a challenge that multiple civil associations, neighborhood groups, conservancies and trusts face. Private or corporate donations, as well as sponsorships and the organization of charity events are successful fundraisers if strategically planned. Learn how to develop financial campaigns and ensure the long-term sustainability of your park in this curricular workshop.', '15', 'Mayo', 2019, '09:00:00', '13:00:00', 'Ana Luisa Ramírez Ramírez, Consultora y Directora, Gestión Filantrópica S.C.', 60, 'Curriculares', 'recaudacion.png'),
(16, 'Marketing y Branding', 'Marketing and Branding ', 'El posicionamiento de una marca en el mercado y en la mente de los consumidores es esencial para el éxito de una empresa, negocio o proyecto. Los parques no son la excepción. La identidad visual de un parque y las estrategias mercadológicas para la atracción de usuarios deben de estar relacionadas con su carisma y con sus objetivos para la creación de lazos duraderos con todos los que lo visitan. Haz que tus eventos, actividades, atracciones y contenido de tu parque sean más visibles para los que los disfrutan.', 'Positioning a brand in the market and in the mind of consumers is essential for the success of a company, business or project. Urban parks are not the exception. The visual identity of a park and the marketing strategies for attracting users must be related to its charisma and objectives for the creation of lasting bonds with all those who visit it. Make your events, activities, attractions and content of your park more visible to those who enjoy them.', '15', 'Mayo', 2019, '15:00:00', '19:00:00', 'Claudia Quintanilla, Director de Marketing & Business Intelligence,Tecnológico de Monterrey, EGADE Escuela de Negocios', 60, 'Curricular', 'mkt_branding.png'),
(17, 'Placemaking', 'Placemaking ', 'El Placemaking (construir lugares) es una metodología para el diseño de espacios públicos que tiene como principios observar, escuchar y preguntar a las personas que lo utilizan y/o viven cerca del sitio que se analiza, o sea, la regeneración urbana de un espacio centrada en los usuarios. En este taller podrás conocer esta metodología, su campo de acción y principios a profundidad, además de llevarla a la práctica analizando espacios de la ciudad sede.', 'Placemaking is a methodology for the design of public spaces whose principles are to observe, listen and ask the people who use it or live near the site being analyzed, so the urban regeneration of a space focused on users. In this workshop you will learn about this methodology, its field of action and in-depth principles, as well as taking it into practice by analyzing spaces in the host city.', '15', 'Mayo', 2019, '15:00:00', '19:00:00', 'Guillermo Bernal, Dirección e Investigación Urbana, Lugares Públicos', 50, 'Curricular', 'placemaking.png'),
(18, 'Gehl Institute', 'Gehl Institute', 'Por segundo año, Congreso Parques la participación del Instituto Gehl en la exposición de su taller curricular sobre estudio de la vida pública en parques urbanos y espacios públicos. Conocer su metodología del análisis y las herramientas de trabajo tropicalizadas a un contexto latinoamericano, en este taller a través del Public Life Toolkit, se discutirá sobre cómo el análisis visual y la observación de lo que las personas hacen en el espacio público puede y debe influir en el diseño y la toma de decisiones; “planear para las personas” es una estrategia que debe incorporarse para el desarrollo urbano sostenible.', 'For the second year, Congreso Parques, the participation of the Gehl Institute in the exhibition of its curricular workshop on the study of public life in urban parks and public spaces. Knowing your analysis methodology and tropicalized work tools in a Latin American context, in this workshop through the Public Life Toolkit, you will discuss how visual analysis and observation of what people do in public space can and should influence in design and decision making; "Planning for people" is a strategy that must be incorporated for sustainable urban development.', '15', 'Mayo', 2019, '10:00:00', '14:00:00', 'Tallerista: Jennifer Gardner, Program Manager, Gehl Institute | Ghigo DiTommaso, Associate, Gehl', 50, 'Curricular', 'ghel.png');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
